apiVersion: v1
kind: Namespace
metadata:
  name: ingress
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: ingress
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  ingress-serviceaccount
  namespace: ingress