apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  name: default-backend
  namespace: kube-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: default-backend
  strategy:
    rollingUpdate:
      maxSurge: 40%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: default-backend
    spec:
      containers:
      - image: denweg/html-image
        name: webapp
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: default-backend
  namespace: kube-system
spec:
  ports:
  - nodePort: 31984
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: default-backend
  type: NodePort